### ISSUE TITLE
Route sorting on homepage doesn't work

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#584] opened 2020-02-27 03:54 UTC
You can use the buttons to try sorting the routes table, but nothing really gets reordered:

![image](https://user-images.githubusercontent.com/728084/75410735-b073a700-58d1-11ea-9ed6-26720dce5479.png)

Also it seems that there are 2 entries for each route...

**Comment by EddyIonescu** [comment] 2020-02-27 04:21
The duplicated entries are being tracked in: https://github.com/trynmaps/metrics-mvp/issues/581
Haven't looked into the re-ordering, will load the page when I get something faster than train Wi-Fi.

**Comment by EddyIonescu** [comment] 2020-02-28 04:21
So the lack of ordering was caused by the rows having duplicate keys for Muni, as they use the route_id (ie. "5R" or "14"). This will be resolved once https://github.com/trynmaps/metrics-mvp/pull/583 is merged. In the meantime I've updated the route file so Muni's now sorted and not duplicated on https://muni.opentransit.city.

**Comment by hathix** [comment] 2020-02-28 22:55
Cool, I updated #583 so it auto closes this.

**Closed** 2020-03-26 01:28 UTC
